name: Publish to GitHub Pages
on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Setup SSH
      uses: MrSquaare/ssh-setup-action@v1
      with:
        host: github.com
        private-key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}

    - name: Build and publish
      env:
        USE_SSH: true
        GIT_USER: vemonet
        # GIT_USER: Nanopublication
      run: |
        cd website
        yarn install
        yarn deploy
